# {'BBC': [{'summary_detail':
#               {'base': u'http://feeds.bbci.co.uk/news/rss.xml',
#                'type': u'text/html',
#                'value': u'Sir John Chilcot says he hopes his report on the Iraq war will ensure future military intervention will be possible only with more careful analysis and political judgement.',
#                'language': None
#                },
#           'published_parsed': time.struct_time(tm_year=2016, tm_mon=7, tm_mday=5, tm_hour=21, tm_min=2, tm_sec=50, tm_wday=1, tm_yday=187, tm_isdst=0),
#           'links': [{'href': u'http://www.bbc.co.uk/news/uk-politics-36712735', 'type': u'text/html', 'rel': u'alternate'}],
#           'title': u"Iraq Inquiry: Chilcot says 'careful analysis needed before war'",
#           'media_thumbnail': [{'url': u'http://c.files.bbci.co.uk/4E83/production/_90299002_mediaitem90299001.jpg', 'width': u'976', 'height': u'549'}],
#           'summary': u'Sir John Chilcot says he hopes his report on the Iraq war will ensure future military intervention will be possible only with more careful analysis and political judgement.',
#           'guidislink': False,
#           'title_detail': {'base': u'http://feeds.bbci.co.uk/news/rss.xml',
#                            'type': u'text/plain', 'value': u"Iraq Inquiry: Chilcot says 'careful analysis needed before war'",
#                            'language': None
#                            },
#           'href': u'',
#           'link': u'http://www.bbc.co.uk/news/uk-politics-36712735',
#           'published': u'Tue, 05 Jul 2016 21:02:50 GMT',
#           'id': u'http://www.bbc.co.uk/news/uk-politics-36712735'
#           }]}


# a = {'movement_name': None,
#      'movement_number': None,
#      'track_type': 'File',
#      'bit_rate': 256,
#      'composer': 'Max Martin, Calvin Broadus, Lukasz Gottwald, Katy Perry, Benjamin Levin & Bonnie McKee',
#      'year': 2010,
#      'size': 7951061,
#      'album': 'California Gurls - Single',
#      'track_count': 1,
#      'rating_computed': False,
#      'comments': None,
#      'track_id': 170,
#      'location': u'D:/iTunes/iTunes Media/Music/Katy Perry/California Gurls - Single/01 California Gurls (feat. Snoop Dog.m4a',
#      'location_escaped': 'file://localhost/D:/iTunes/iTunes%20Media/Music/Katy%20Perry/California%20Gurls%20-%20Single/01%20California%20Gurls%20(feat.%20Snoop%20Dog.m4a',
#      'total_time': 236220, 'movement_count': None, 'compilation': False,
#      'date_modified': time.struct_time(tm_year=2015, tm_mon=7, tm_mday=15, tm_hour=10, tm_min=35, tm_sec=49, tm_wday=2,
#                                        tm_yday=196, tm_isdst=-1), 'genre': '[Pop',
#      'date_added': time.struct_time(tm_year=2017, tm_mon=1, tm_mday=17, tm_hour=4, tm_min=6, tm_sec=8, tm_wday=1,
#                                     tm_yday=17, tm_isdst=-1), 'album_artist': 'Katy Perry',
#      'kind': u'\u5df2\u8d2d\u4e70\u7684 AAC \u97f3\u9891\u6587\u4ef6', 'name': 'California Gurls (feat. Snoop Dogg)',
#      'artist': 'Katy Perry',
#      'work': None, 'persistent_id': '1D38EB13E75BD1B5',
#      'track_number': 1,
#      'length': 236220,
#      'sample_rate': 44100}


# b = {'template_folder': 'templates',
#      'error_handler_spec': {None: {}},
#      'before_request_funcs': {None: [<function before_request at 0x7fe5c858ef50>]},
# 'teardown_appcontext_funcs': [<function shutdown_session at 0x7fe5c8627c08>],
# '_before_request_lock': <thread.lock object at 0x7fe5c874b610>,
#                                                'after_request_funcs': {None: [<bound method LoginManager._update_remember_cookie of <flask_login.LoginManager object at 0x7fe5c91d8e10>>]},
# 'before_first_request_funcs': [],
#                               'view_functions': {'auth.edit_profile_admin': <function edit_profile_admin at 0x7fe5c859a848>,
#                                                                                                             'auth.user': <function user at 0x7fe5c859a578>,
#                                                                                                                                            'main.fetch_news': <function fetch_news at 0x7fe5c86299b0>,
#                                                                                                                                                                                       'auth.edit_profile': <function edit_profile at 0x7fe5c859a6e0>, 'auth.signin': <function signin at 0x7fe5c859a050>, 'main.index': <function index at 0x7fe5c8629758>, 'api.hw_monitor': <function hw_monitor at 0x7fe5c859ab18>, 'static': <bound method Flask.send_static_file of <Flask 'app'>>, 'auth.signout': <function signout at 0x7fe5c859a2a8>, 'auth.signup': <function signup at 0x7fe5c859a140>, 'api.favourites': <function favourites at 0x7fe5c859ac08>, 'auth.weibo': <function weibo at 0x7fe5c859a398>, 'auth.qq': <function qq at 0x7fe5c859a488>}, 'instance_path': '/home/tete/N/instance', 'teardown_request_funcs': {}, 'login_manager': <flask_login.LoginManager object at 0x7fe5c91d8e10>, 'url_value_preprocessors': {}, 'config': <Config {'JSON_AS_ASCII': True, 'USE_X_SENDFILE': False, 'SQLALCHEMY_DATABASE_URI': 'sqlite:////home/tete/N/data.sqlite', 'CELERY_RESULT_SERIALIZER': 'json', 'SQLALCHEMY_POOL_SIZE': None, 'SQLALCHEMY_POOL_TIMEOUT': None, 'SESSION_COOKIE_PATH': None, 'SQLALCHEMY_RECORD_QUERIES': None, 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_NAME': 'session', 'SQLALCHEMY_BINDS': None, 'CELERY_BROKER_URL': 'redis://localhost:6379/0', 'LOGGER_NAME': 'app', 'CELERY_TIMEZONE': 'Asia/Shanghai', 'DEBUG': True, 'SQLALCHEMY_COMMIT_ON_TEARDOWN': True, 'SECRET_KEY': '$%^NB4%^#_+UHha', 'CELERY_RESULT_BACKEND': 'redis://localhost:6379/0', 'SQLALCHEMY_TRACK_MODIFICATIONS': True, 'SQLALCHEMY_NATIVE_UNICODE': None, 'MAX_CONTENT_LENGTH': None, 'WEIBO_APP_SECRET': 'cf1eb69ab2ea726b1b0542da97160c52', 'SQLALCHEMY_ECHO': True, 'APPLICATION_ROOT': None, 'SERVER_NAME': None, 'PREFERRED_URL_SCHEME': 'http', 'JSONIFY_PRETTYPRINT_REGULAR': True, 'TESTING': False, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(31), 'PROPAGATE_EXCEPTIONS': None, 'WEIBO_CALLBACK_URI': 'http://tetewechat.ngrok.cc/oauth/weibo', 'TRAP_BAD_REQUEST_ERRORS': False, 'SQLALCHEMY_POOL_RECYCLE': None, 'JSON_SORT_KEYS': True, 'CELERYBEAT_SCHEDULE': {'cache-news-image-every-2-hours': {'task': 'tasks.cache_image', 'schedule': <crontab: 0 */2 * * * (m/h/d/dM/MY)>}, 'refresh-weather-every-30-minutes': {'task': 'tasks.refresh_weather', 'args': ('Tianjin',), 'schedule': <crontab: */30 * * * * (m/h/d/dM/MY)>}, 'refresh-news-every-hour': {'task': 'tasks.fetch_news', 'args': (50,), 'schedule': <crontab: 0 */1 * * * (m/h/d/dM/MY)>}}, 'SQLALCHEMY_MAX_OVERFLOW': None, 'SESSION_COOKIE_HTTPONLY': True, 'SEND_FILE_MAX_AGE_DEFAULT': 43200, 'WEIBO_APP_KEY': '3797168746', 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SESSION_COOKIE_SECURE': False, 'TRAP_HTTP_EXCEPTIONS': False}>, '_static_url_path': None, '_logger': None, 'template_context_processors': {None: [<function _default_template_ctx_processor at 0x7fe5ca534500>, <function _user_context_processor at 0x7fe5c99f7c80>]}, '_error_handlers': {}, 'blueprints': {'api': <flask.blueprints.Blueprint object at 0x7fe5c8599110>, 'main': <flask.blueprints.Blueprint object at 0x7fe5c8633850>, 'auth': <flask.blueprints.Blueprint object at 0x7fe5c8633950>}, 'url_map': Map([<Rule '/api/v1/favourites' (HEAD, POST, GET, OPTIONS, DELETE) -> api.favourites>,
# <Rule '/api/v1/hw_status' (HEAD, OPTIONS, GET) -> api.hw_monitor>,
# <Rule '/oauth/weibo' (HEAD, OPTIONS, GET) -> auth.weibo>,
# <Rule '/oauth/qq' (HEAD, OPTIONS, GET) -> auth.qq>,
# <Rule '/edit-profile-admin' (HEAD, POST, OPTIONS, GET) -> auth.edit_profile_admin>,
# <Rule '/edit-profile' (HEAD, POST, OPTIONS, GET) -> auth.edit_profile>,
# <Rule '/fetchnews' (HEAD, POST, OPTIONS, GET) -> main.fetch_news>,
# <Rule '/signout' (HEAD, OPTIONS, GET) -> auth.signout>,
# <Rule '/signin' (HEAD, POST, OPTIONS, GET) -> auth.signin>,
# <Rule '/signup' (HEAD, POST, OPTIONS, GET) -> auth.signup>,
# <Rule '/' (HEAD, POST, OPTIONS, GET) -> main.index>,
# <Rule '/static/<filename>' (HEAD, OPTIONS, GET) -> static>,
# <Rule '/user/<user_id>' (HEAD, OPTIONS, GET) -> auth.user>]), 'name': 'app', '_got_first_request': False, 'import_name': 'app', 'root_path': '/home/tete/N/app', '_static_folder': 'static', 'extensions': {'migrate': <flask_migrate._MigrateConfig object at 0x7fe5c8599550>, 'sqlalchemy': <flask_sqlalchemy._SQLAlchemyState object at 0x7fe5c86337d0>}, 'url_default_functions': {}, 'url_build_error_handlers': []}
